SCR_MissionHeader {
 World "{6D417399ED326D02}World/GM_Saigon.ent"
 m_sName "Game Master - Saigon"
 m_sAuthor "Map by Rustyhook96, Scenario by Geek-x"
 m_sDescription "Saigon in Game Master."
 m_iPlayerCount 64
}